#!/usr/bin/env python

"""
Docstring will go here

"""

import collections
import string
import subprocess
import sys
import itertools
import re
from urllib.request import urlopen
from bs4 import BeautifulSoup as soup
import requests

__author__ = "Paweł Kwiatkowski"
__copyright__ = "Copyright 2018, Paweł Kwiatkowski"
__credits__ = [
    "Paweł Kwiatkowski"]  # includes people who reported bug fixes, made suggestions, etc. but did not actually write the code
__license__ = "GPL"
__version__ = "1.0.0"
__maintainer__ = "Paweł Kwiatkowski"  # should be the person who will fix bugs and make improvements if imported.
__email__ = "kwiatkowski.pawel87@gmail.com"
__status__ = "Production"  # "Prototype", "Development" or "Production"


def main():
    my_url = 'https://www.priberam.pt/dlpo/Conjugar/dizer'

    with urlopen(my_url) as page_to_download:
        file_to_see = page_to_download.read()
        page_soup = soup(file_to_see, 'lxml')
        list_of_conjugations = list(page_soup.find_all('div', class_='tdCONJ'))
        final = []

        for e in list_of_conjugations:
            e = str(e)
            final.append(e)

        all = []
        pattern = re.compile(r'(di)[^v]\w+')
        matches = re.finditer(pattern, ', '.join(final))
        for match in matches:
            match = str(match)
            all.append(match)

        # for a in all:
        #     print(a, end='')

        my = []

        for e in all:
            my.append(e.split('='))

        wreszcie = []

        for e in my:
            wreszcie.append(e[-1].strip("'>"))

        # print(wreszcie)

        for run in range(10):
            pass

        divided = [wreszcie[i:i + 5] for i in range(0, len(wreszcie), 5)]

        print(divided)

        # final = list()
        # for e in list_of_conjugations:
        #     final.append(e.text)
    #
    # a = []
    # for t in final:
    #     a.append(t.split())
    #
    # for t in a:
    #     print(t)


if __name__ == '__main__':
    main()
